project_name: myproject
release:
  github:
    owner: your-github-username
    name: your-repo-name
builds:
  - os: linux
    goamd64: amd64
    main: ./cmd/myproject/main.go
    binary: myproject
archives:
  - format: zip
    files:
      - myproject
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'