name: Test and build Go
on: [push, pull_request]
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2


    - name: Install staticcheck
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: |
        staticcheck ./...

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.23.x]
    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test
      run: go test -v .

    - name: Build
      run: go build -v .
